#!/usr/bin/bash 

rg ./ --line-number | fzf --preview='set line {2} && set begin ( test $line -lt 11  &&  echo (math "$line-1") || echo  10 ) && bat --highlight-line={2} --color=always --line-range (math "$line-$begin"):(math "$line+10") {1}' --delimiter=':'
